apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    app: nginx
    env: prod
spec:
  containers:
  - name: nginx
    image: twalter/openshift-nginx
    ports:
    - containerPort: 8081
