apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    component: wordpress
spec:
  ports:
    - port: 8081
  selector:
    app: wordpress
    component: wordpress
  type: NodePort